plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
  id 'kotlin-kapt'
}

group = 'expo.modules.openbeacontracking'
version = '0.0.0'

android {
  namespace "expo.modules.openbeacontracking"
  defaultConfig {
    versionCode 1
    versionName "0.0.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation "com.google.crypto.tink:tink-android:1.18.0"
  implementation "com.google.android.gms:play-services-location:21.0.1"
  implementation "androidx.core:core-ktx:1.17.0"
  implementation "androidx.room:room-runtime:2.8.4"
  implementation "androidx.room:room-ktx:2.8.4"
  kapt "androidx.room:room-compiler:2.8.4"
}
